version: "3.8"

services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    platform: linux/arm64
    container_name: inventory-db
    # إيقاف ONLY_FULL_GROUP_BY لتجنب خطأ الـ SQL
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64  # phpMyAdmin لا يدعم arm64، لذلك نستخدم amd64
    container_name: ci4_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data:
